{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kernel/0.5.0/kernel-0.5.0.module",
    "group": "dev.modaal.duet",
    "module": "kernel",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kernel-iosArm64Main-0.5.0.klib",
          "url": "kernel-iosarm64-0.5.0.klib",
          "size": 60237,
          "sha512": "cef2ad97228512becdd332224bbb0010bacf085d3ff9ccd49178e15ddb1d8b62d7285441c6fa3764dd0b7d236d8167e4827ce505ab3992191a652d804f34c941",
          "sha256": "cde8ae845883cc8519935ee0e996b05fb301416b5f309c2396bbafeceab901e1",
          "sha1": "40cacd1e0fd3833e04810d43adaaecbfe2c7bf30",
          "md5": "8112d1b4793dc113ab3ef65237429c76"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kernel-iosarm64-0.5.0-sources.jar",
          "url": "kernel-iosarm64-0.5.0-sources.jar",
          "size": 22244,
          "sha512": "2039606e917d0e022636bc10f5eeb91dc10d86fc8b849582ff05f0a81f5c9016f4ca2abb0e060db0481e3dbf4d8c78280a4c05fb736b93b34319898f7f7eb99d",
          "sha256": "d79bd526e229a10cb84abd39e3fae732ad45d735ffcfe8fb08a2bfafb506c434",
          "sha1": "098aaff1d9c2c9fb849224d998d676c6c8a7695b",
          "md5": "139c99f7d1b81b415e370dd655f9df93"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kernel-iosarm64-0.5.0-metadata.jar",
          "url": "kernel-iosarm64-0.5.0-metadata.jar",
          "size": 2738,
          "sha512": "1b48f6b3dbb065a3f7311bea9fbd151478f3c54e09f5884c74959e2b68be2575fa558c35d62d7f6e8863d259efc4828493af87a7b4f0754166d2e3b424529d8a",
          "sha256": "4d0fded5acd155c9ba7e19c79215f960fc7f265d5713148e7beb69ebf6caf0f1",
          "sha1": "9b1c2aa6f8aa4029e1347f3af146ee89c3b84397",
          "md5": "c005b7b7050502fc99884811aa6ff873"
        }
      ]
    }
  ]
}
