{
  "formatVersion": "1.1",
  "component": {
    "url": "../../theming/0.8.0/theming-0.8.0.module",
    "group": "dev.modaal.duet.services",
    "module": "theming",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "theming-jvm-0.8.0.jar",
          "url": "theming-jvm-0.8.0.jar",
          "size": 21694,
          "sha512": "b344204c9a169facffeffeca34c45629afdfc8b794dca322eba0597f69c580c302a5d5a49501f20759a7290d6d96ca0b45d86f2780eae393f188dc4e059428cf",
          "sha256": "fb0348dcde85dcf0706c8d7989299853b694a2585f0c6a00e4588acfa7d13852",
          "sha1": "92438a23223861c1eadd1f00ed482c834b7b963f",
          "md5": "3149cd85825fba635ee560b8ae8d1649"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "theming-jvm-0.8.0.jar",
          "url": "theming-jvm-0.8.0.jar",
          "size": 21694,
          "sha512": "b344204c9a169facffeffeca34c45629afdfc8b794dca322eba0597f69c580c302a5d5a49501f20759a7290d6d96ca0b45d86f2780eae393f188dc4e059428cf",
          "sha256": "fb0348dcde85dcf0706c8d7989299853b694a2585f0c6a00e4588acfa7d13852",
          "sha1": "92438a23223861c1eadd1f00ed482c834b7b963f",
          "md5": "3149cd85825fba635ee560b8ae8d1649"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "theming-jvm-0.8.0-sources.jar",
          "url": "theming-jvm-0.8.0-sources.jar",
          "size": 6606,
          "sha512": "2c1b6272553aaa156455339dc0e902bf094bf96839bd47528e5143d2daea252ccf3528925a48e18ad684a748e861a9f38fbf789c844147d4d02706bb051fc4e8",
          "sha256": "5d7507a4ee54ad4cbd48be95291518cac6d9ed852ea7f67d04a37558b6cc67d4",
          "sha1": "d0bf7d1954b538c669658d9809d9152a952ea4c0",
          "md5": "bf53c7fbc4b2ccbd26c87dc494948da3"
        }
      ]
    }
  ]
}
