{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.modaal.duet",
    "module": "kernel-test",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.modaal.duet",
          "module": "kernel",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "dev.modaal.duet",
          "module": "shells-compose",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "kernel-test-0.4.0.jar",
          "url": "kernel-test-0.4.0.jar",
          "size": 151081,
          "sha512": "80a71ed69f07bcb34e222231af7ae8b3d162d6969a8985b0bcf590ff7a549285624375dede867d4a80e8fd81ab59ec9d99bee56703f1a8babc6edf45a4e99dd8",
          "sha256": "408102112e0ff4f07720dda2ef7782746979d85c5494d41fb99fb810366ec528",
          "sha1": "9ab3e0b332b3debfee68687a0cc2e28d860982db",
          "md5": "e77380b881bb4d72fa2a4c048e6a0f71"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test"
        },
        {
          "group": "dev.modaal.duet",
          "module": "kernel",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "dev.modaal.duet",
          "module": "shells-compose",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "kernel-test-0.4.0.jar",
          "url": "kernel-test-0.4.0.jar",
          "size": 151081,
          "sha512": "80a71ed69f07bcb34e222231af7ae8b3d162d6969a8985b0bcf590ff7a549285624375dede867d4a80e8fd81ab59ec9d99bee56703f1a8babc6edf45a4e99dd8",
          "sha256": "408102112e0ff4f07720dda2ef7782746979d85c5494d41fb99fb810366ec528",
          "sha1": "9ab3e0b332b3debfee68687a0cc2e28d860982db",
          "md5": "e77380b881bb4d72fa2a4c048e6a0f71"
        }
      ]
    }
  ]
}
