{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.modaal.duet.services",
    "module": "theming",
    "version": "0.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "theming-metadata-0.11.0.jar",
          "url": "theming-0.11.0.jar",
          "size": 5888,
          "sha512": "6cb0dd3a4a89dc89282108001dedcdae2332cbba1a0d25e967d6043b8fdf1d0f7d39dd9bd93e17b759e47a50dff7a66d94c94fc5e414765b2ba89a9c5a8696c3",
          "sha256": "d773ac8304f3f654e8f9733408b3540900e023075f67aad7cab08b566379f734",
          "sha1": "f5e0401b679884a92fd11dcc490e298e29655615",
          "md5": "e30580184a386dffde0c2e265a34d807"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "theming-kotlin-0.11.0-sources.jar",
          "url": "theming-0.11.0-sources.jar",
          "size": 6606,
          "sha512": "2c1b6272553aaa156455339dc0e902bf094bf96839bd47528e5143d2daea252ccf3528925a48e18ad684a748e861a9f38fbf789c844147d4d02706bb051fc4e8",
          "sha256": "5d7507a4ee54ad4cbd48be95291518cac6d9ed852ea7f67d04a37558b6cc67d4",
          "sha1": "d0bf7d1954b538c669658d9809d9152a952ea4c0",
          "md5": "bf53c7fbc4b2ccbd26c87dc494948da3"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../theming-iosarm64/0.11.0/theming-iosarm64-0.11.0.module",
        "group": "dev.modaal.duet.services",
        "module": "theming-iosarm64",
        "version": "0.11.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../theming-iosarm64/0.11.0/theming-iosarm64-0.11.0.module",
        "group": "dev.modaal.duet.services",
        "module": "theming-iosarm64",
        "version": "0.11.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../theming-iosarm64/0.11.0/theming-iosarm64-0.11.0.module",
        "group": "dev.modaal.duet.services",
        "module": "theming-iosarm64",
        "version": "0.11.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../theming-iossimulatorarm64/0.11.0/theming-iossimulatorarm64-0.11.0.module",
        "group": "dev.modaal.duet.services",
        "module": "theming-iossimulatorarm64",
        "version": "0.11.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../theming-iossimulatorarm64/0.11.0/theming-iossimulatorarm64-0.11.0.module",
        "group": "dev.modaal.duet.services",
        "module": "theming-iossimulatorarm64",
        "version": "0.11.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../theming-iossimulatorarm64/0.11.0/theming-iossimulatorarm64-0.11.0.module",
        "group": "dev.modaal.duet.services",
        "module": "theming-iossimulatorarm64",
        "version": "0.11.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../theming-jvm/0.11.0/theming-jvm-0.11.0.module",
        "group": "dev.modaal.duet.services",
        "module": "theming-jvm",
        "version": "0.11.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../theming-jvm/0.11.0/theming-jvm-0.11.0.module",
        "group": "dev.modaal.duet.services",
        "module": "theming-jvm",
        "version": "0.11.0"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../theming-jvm/0.11.0/theming-jvm-0.11.0.module",
        "group": "dev.modaal.duet.services",
        "module": "theming-jvm",
        "version": "0.11.0"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../theming-macosarm64/0.11.0/theming-macosarm64-0.11.0.module",
        "group": "dev.modaal.duet.services",
        "module": "theming-macosarm64",
        "version": "0.11.0"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../theming-macosarm64/0.11.0/theming-macosarm64-0.11.0.module",
        "group": "dev.modaal.duet.services",
        "module": "theming-macosarm64",
        "version": "0.11.0"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../theming-macosarm64/0.11.0/theming-macosarm64-0.11.0.module",
        "group": "dev.modaal.duet.services",
        "module": "theming-macosarm64",
        "version": "0.11.0"
      }
    }
  ]
}
