{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kernel/0.3.0/kernel-0.3.0.module",
    "group": "dev.modaal.duet",
    "module": "kernel",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "kernel-macosArm64Main-0.3.0.klib",
          "url": "kernel-macosarm64-0.3.0.klib",
          "size": 64121,
          "sha512": "37881755e04a370409c4f9d4e1b91cd05eb1a02d2dc5b272707e802a31f4730b87edf12771050ce96226250a8bc10167384cdedfc947e6673df715c94dc2d2be",
          "sha256": "c67ce3614d42394355a7ef01aba65595da857c8fa6106432606247d51202002a",
          "sha1": "655a913c6638b7f26b6b86f26474cbcc4f1f1bd5",
          "md5": "dad1864a02cf1555bf8a4abfee965e90"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kernel-macosarm64-0.3.0-sources.jar",
          "url": "kernel-macosarm64-0.3.0-sources.jar",
          "size": 22244,
          "sha512": "2039606e917d0e022636bc10f5eeb91dc10d86fc8b849582ff05f0a81f5c9016f4ca2abb0e060db0481e3dbf4d8c78280a4c05fb736b93b34319898f7f7eb99d",
          "sha256": "d79bd526e229a10cb84abd39e3fae732ad45d735ffcfe8fb08a2bfafb506c434",
          "sha1": "098aaff1d9c2c9fb849224d998d676c6c8a7695b",
          "md5": "139c99f7d1b81b415e370dd655f9df93"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "kernel-macosarm64-0.3.0-metadata.jar",
          "url": "kernel-macosarm64-0.3.0-metadata.jar",
          "size": 2711,
          "sha512": "f893e6d00926f332ba490a258b5928ef6c36811676613e21630b9d4e02cdb8ff837a3edb3d5039d210e0c46d84827ff7472ae198e749ba6e14d191423d61b027",
          "sha256": "7907dcab26884caa7894539b1ac5760bd4fa64fb785a80c20cb0cccfb7a12eab",
          "sha1": "fa5eb865dc920b092dcd891bbc4f72e501b534b5",
          "md5": "34c57d722a9ffc7e058ef3c2f8ef66c4"
        }
      ]
    }
  ]
}
