{
  "formatVersion": "1.1",
  "component": {
    "url": "../../theming/0.12.0/theming-0.12.0.module",
    "group": "dev.modaal.duet.services",
    "module": "theming",
    "version": "0.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "theming-iosSimulatorArm64Main-0.12.0.klib",
          "url": "theming-iossimulatorarm64-0.12.0.klib",
          "size": 20815,
          "sha512": "4a70088276a48151ef2634e2a01485d591a223f6c1a6fe07bd514ce26e2c6956f2ed3d43d1b3182b990229a524264469d2f3908a93b33d6612e23e3a48ae3a5e",
          "sha256": "206224414460a28879e9635d27dc7d07760b3108625d7c174222adae6d6546bd",
          "sha1": "96e037f9f038eed3697d493117c34cca30ca7c1e",
          "md5": "deaf240c06476e49fa96655832bf7dcf"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "theming-iossimulatorarm64-0.12.0-sources.jar",
          "url": "theming-iossimulatorarm64-0.12.0-sources.jar",
          "size": 6934,
          "sha512": "1a48a508c10964d541bdc2ddaf1a950db23a27349d3d0827848b52b12c221abc25c9292f281e70b8fd682ea3283dfde8f80061028c769606fa64bf48f6743dfd",
          "sha256": "026ab17013d510c78ff9acc2dfaee0f71319da819cd4527d33d22b11f8baeaf0",
          "sha1": "d83f2589e14cde3a7c302b4ab5700d3c738ab068",
          "md5": "262c195a7c819ec37dd3397c937d9e86"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "theming-iossimulatorarm64-0.12.0-metadata.jar",
          "url": "theming-iossimulatorarm64-0.12.0-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
