{
  "formatVersion": "1.1",
  "component": {
    "url": "../../theming/0.9.0/theming-0.9.0.module",
    "group": "dev.modaal.duet.services",
    "module": "theming",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "theming-macosArm64Main-0.9.0.klib",
          "url": "theming-macosarm64-0.9.0.klib",
          "size": 19714,
          "sha512": "9819dc44e4da464a51b0a36c9f47b6a87ee8917b11bb67339d80815fd7d1abbb6557e05f67ec171eed273758ea0526d010781f7421a730e386d8caad025f523b",
          "sha256": "b5bb3e295c89ce3c77d762e24418150cd211ad0b5e942f089ba3f15c3c891749",
          "sha1": "88aca8f3edcf359a52b802f3733985d738ec1099",
          "md5": "617d20935249def92d039cc2762786c0"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "theming-macosarm64-0.9.0-sources.jar",
          "url": "theming-macosarm64-0.9.0-sources.jar",
          "size": 6606,
          "sha512": "2c1b6272553aaa156455339dc0e902bf094bf96839bd47528e5143d2daea252ccf3528925a48e18ad684a748e861a9f38fbf789c844147d4d02706bb051fc4e8",
          "sha256": "5d7507a4ee54ad4cbd48be95291518cac6d9ed852ea7f67d04a37558b6cc67d4",
          "sha1": "d0bf7d1954b538c669658d9809d9152a952ea4c0",
          "md5": "bf53c7fbc4b2ccbd26c87dc494948da3"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "theming-macosarm64-0.9.0-metadata.jar",
          "url": "theming-macosarm64-0.9.0-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
